name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@v1

    - name: Build Batocera
      run: make x86_64-build

    - uses: softprops/action-gh-release@v1
      with:
        files: ./output/images/batocera/images/x86_64/*
